name: Notify Package Managers

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  dispatch:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.TAP_DISPATCH_TOKEN }}
      TAG: ${{ github.event.release.tag_name }}
    steps:
      - name: Validate tag
        run: |
          if [ -z "$TAG" ]; then
            echo "release tag_name is empty" >&2
            exit 1
          fi

      - name: Dispatch to Homebrew tap
        run: |
          set -euo pipefail
          curl -sSf -X POST \
            -H "Authorization: token ${GH_TOKEN}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/zhaochengcube/homebrew-atm/dispatches \
            -d "$(jq -n --arg tag "$TAG" '{event_type:"atm_release", client_payload:{tag:$tag}}')"

      - name: Dispatch to Scoop bucket
        run: |
          set -euo pipefail
          curl -sSf -X POST \
            -H "Authorization: token ${GH_TOKEN}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/zhaochengcube/scoop-atm/dispatches \
            -d "$(jq -n --arg tag "$TAG" '{event_type:"atm_release", client_payload:{tag:$tag}}')"
